branches:
  only:
    - master
    - /^.*travis.*$/
    - /^greenkeeper/.*$/

  except:
    - /^v\d+\.\d+\.\d+$/

sudo: required
dist: trusty
group: deprecated-2017Q4

language: node_js
node_js:
  - '9'
  - '8'
  - '6'

services:
  - mongodb
  - neo4j

before_install:
  - if [[ `npm -v` != 6* ]]; then npm install -g npm@6; fi

install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;

notifications:
  email: false

before_script:
  - sleep 15

script:
  - npm run test-travis

after_success:
  - npm run travis-deploy-once "npm run semantic-release && npm run coveralls"
