branches:
  only:
    - master
    - /^.*travis.*$/
    - /^greenkeeper/.*$/

  except:
    - /^v\d+\.\d+\.\d+$/

sudo: required

language: node_js
node_js:
  - '10'
  - '12'
  - '14'

jdk: openjdk11

services:
  - mongodb

env:
  - NEO4J_VERSION="4.1.0"

cache:
  directories:
    - ~/.npm

before_install:
  - if [[ `npm -v` != 6* ]]; then npm install -g npm@6; fi

install:
  - case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
  - mkdir -p /tmp/neo4j
  - cd /tmp/neo4j
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - /tmp/neo4j/neo4j-community-$NEO4J_VERSION/bin/neo4j-admin set-initial-password $NEO_PASS
  - /tmp/neo4j/neo4j-community-$NEO4J_VERSION/bin/neo4j start
  - cd $TRAVIS_BUILD_DIR

notifications:
  email: false

before_script:
  - sleep 15

script:
  - npm run test-travis

after_success:
  - npm run travis-deploy-once "npm run semantic-release && npm run coveralls"
