branches:
  only:
    - master
    - /^.*travis.*$/
    - /^greenkeeper/.*$/

  except:
    - /^v\d+\.\d+\.\d+$/

sudo: required
dist: trusty
group: deprecated-2017Q4

language: node_js
node_js:
  - '10'
  - '12'
  - '14'

services:
  - mongodb
  - neo4j

cache:
  directories:
    - ~/.npm

before_install:
  - if [[ `npm -v` != 6* ]]; then npm install -g npm@6; fi

install:
  - case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
  - wget dist.neo4j.org/neo4j-community-4.1.0-unix.tar.gz
  - tar -xzf neo4j-community-4.1.0-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-4.1.0/conf/neo4j-server.properties
  - neo4j-community-4.1.0/bin/neo4j start

notifications:
  email: false

before_script:
  - sleep 15

script:
  - npm run test-travis

after_success:
  - npm run travis-deploy-once "npm run semantic-release && npm run coveralls"
