version: "3"

services:
  mongo4j:
    image: svenwstrl/mongo4j
    build: ./
    depends_on:
      - neo4j
      - mongodb
    volumes:
      - .:/usr/src/app
    environment:
      MONGO_URI: mongodb
      NEO_URI: neo4j://neo4j
      NEO_USER: neo4j
      NEO_PASS: new
    tty: true

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/new
      NEO4J_dbms_security_auth__minimum__password__length: 3

  mongodb:
    image: mongo
